### ISSUE TITLE
Consider translations

### ISSUE THREAD

**Issue by emilebosch** [kuroda/multi_tenancy#3]
Hi! 

I think this is what I want! 👍 However I can't read your language, would you like to translate it?

**Comment by sbiastoch** [comment]
Indeed, RLS is an awesome feature of postgres and Rails applications despite used often for SaaS  lack a low level mechanism to enforce data separation. If you guys switch to english this will be much more accessible for others to use and contribute. It really looks very promising yet!

**Comment by kuroda** [comment]
@emilebosch @sbiastoch 

I'll think about it. Thank you for your interest.

**Comment by kuroda** [comment]
@emilebosch @sbiastoch 

I made the English version of README.md with help of Google translation service.

Please correct if there are grammar mistakes or wrong wordings.

**Comment by emilebosch** [comment]
Thank you kuroda!
